source 'https://cdn.cocoapods.org/'

target 'FaceSwiftUI-sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FaceSwiftUI-sample
  pod 'FaceSDK', '~> 7.1'
  pod 'FaceCoreBasic', '~> 7.1'
end
