source 'http://gitlab.regula.local/mobile-sdk/podspecs.git'
source 'https://cdn.cocoapods.org/'

target 'FaceSwiftUI-sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FaceSwiftUI-sample
  pod 'FaceSDK', '~> 5.2'
  pod 'FaceCoreSDK', '~> 5.2'
end
