# Uncomment the next line to define a global platform for your project
platform :ios, '17.0'

target 'FaceMatchOffline-sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'FaceSDK', '~> 6.1.1743'
  pod 'FaceCoreMatch', '~> 6.1.571'
end
