# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
use_frameworks!

target 'FaceMatchOffline-sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'FaceSDK', '~> 7.2'
  pod 'FaceCoreMatch', '~> 7.2'
end
