# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'FaceCertificatePinning' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'FaceSDK', '~> 6.1'
  pod 'FaceCoreBasic', '~> 6.1'
end
